#!/usr/bin/env python3
"""
Debug force control in run_sim to see what's happening.
"""

import sys
import os
import numpy as np

# Add the project root to the path
sys.path.insert(0, os.getcwd())

def debug_force_control():
    """Debug force control step by step."""
    print("Debug Force Control")
    print("=" * 30)
    
    # Import here to avoid path issues
    from environment.soft_robotic_env import SoftRobotic
    
    # Create environment
    env = SoftRobotic(control_mode="force", render_mode=None)
    obs, info = env.reset()
    
    print(f"Initial theta: {obs[2]:.6f}")
    print(f"Action space: low={env.action_space.low}, high={env.action_space.high}")
    
    # Test with large forces
    print("\nTesting with large forces [800, 100]:")
    action = np.array([800.0, 100.0], dtype=np.float32)
    print(f"Action: {action}")
    
    obs, reward, terminated, truncated, info = env.step(action)
    
    print(f"After step:")
    print(f"  Theta: {obs[2]:.6f}")
    print(f"  Left force applied: {info.get('force_left', 'N/A')}")
    print(f"  Right force applied: {info.get('force_right', 'N/A')}")
    print(f"  Torque: {info.get('tau', 'N/A')}")
    print(f"  Reward: {reward}")
    
    # Test a few more steps
    print("\nTesting additional steps:")
    for i in range(5):
        obs, reward, terminated, truncated, info = env.step(action)
        print(f"  Step {i+1}: Theta={obs[2]:.6f}, Tau={info.get('tau', 'N/A'):.2f}")
    
    env.close()

def debug_runner_forces():
    """Debug what forces the runner is actually generating."""
    print("\nDebug Runner Force Generation")
    print("=" * 30)
    
    # Simulate what the runner does
    sinusoidal_magnitude = 0.5  # Default value
    sinusoidal_frequency = 0.2  # Default value
    time_step = 0.02  # Standard time step
    
    print(f"Runner parameters:")
    print(f"  Sinusoidal magnitude: {sinusoidal_magnitude}")
    print(f"  Sinusoidal frequency: {sinusoidal_frequency}")
    print(f"  Time step: {time_step}")
    
    print(f"\nFirst 10 forces generated by runner:")
    for i in range(10):
        t = i * time_step
        left_force = sinusoidal_magnitude * np.sin(2.0 * np.pi * sinusoidal_frequency * t)
        right_force = sinusoidal_magnitude * np.sin(2.0 * np.pi * sinusoidal_frequency * t + np.pi/4)
        print(f"  Step {i}: [{left_force:6.3f}, {right_force:6.3f}]")
    
    print(f"\nWith larger magnitude (600):")
    sinusoidal_magnitude = 600.0
    for i in range(10):
        t = i * time_step
        left_force = sinusoidal_magnitude * np.sin(2.0 * np.pi * sinusoidal_frequency * t)
        right_force = sinusoidal_magnitude * np.sin(2.0 * np.pi * sinusoidal_frequency * t + np.pi/4)
        print(f"  Step {i}: [{left_force:6.1f}, {right_force:6.1f}]")

if __name__ == "__main__":
    debug_force_control()
    debug_runner_forces()